// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AudioConfig { codec2Enabled: boolean, pttPin: number, bitrate: number, i2SWs: number, i2SSd: number, i2SDin: number, i2SSck: number, }