// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ChannelSettings { channelNum: number, psk: Array<number>, name: string, id: number, uplinkEnabled: boolean, downlinkEnabled: boolean, }