// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelSettings } from "./ChannelSettings";

export interface Channel { index: number, settings: ChannelSettings | null, role: number, }