// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";

export interface ChannelFile { channels: Array<Channel>, version: number, }