// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelSettings } from "./ChannelSettings";
import type { LoRaConfig } from "./LoRaConfig";

export interface ChannelSet { settings: Array<ChannelSettings>, loraConfig: LoRaConfig | null, }