// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Data { portnum: number, payload: Array<number>, wantResponse: boolean, dest: number, source: number, requestId: number, replyId: number, emoji: number, }