// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DeviceConfig { role: number, serialEnabled: boolean, debugLogEnabled: boolean, buttonGpio: number, buzzerGpio: number, }