// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DeviceMetrics { batteryLevel: number, voltage: number, channelUtilization: number, airUtilTx: number, }