// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DeviceMetadata { firmwareVersion: string, deviceStateVersion: number, canShutdown: boolean, hasWifi: boolean, hasBluetooth: boolean, hasEthernet: boolean, role: number, positionFlags: number, }