// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DisplayConfig { screenOnSecs: number, gpsFormat: number, autoScreenCarouselSecs: number, compassNorthTop: boolean, flipScreen: boolean, units: number, oled: number, displaymode: number, headingBold: boolean, }