// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EnvironmentMetrics { temperature: number, relativeHumidity: number, barometricPressure: number, gasResistance: number, voltage: number, current: number, }