// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ExternalNotificationConfig { enabled: boolean, outputMs: number, output: number, active: boolean, alertMessage: boolean, alertBell: boolean, }