// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayloadVariant } from "./PayloadVariant";

export interface FromRadio { id: number, payloadVariant: PayloadVariant | null, }