// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Level = "unset" | "critical" | "error" | "warning" | "info" | "debug" | "trace";