// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioConfig } from "./AudioConfig";
import type { CannedMessageConfig } from "./CannedMessageConfig";
import type { ExternalNotificationConfig } from "./ExternalNotificationConfig";
import type { MqttConfig } from "./MqttConfig";
import type { RangeTestConfig } from "./RangeTestConfig";
import type { RemoteHardwareConfig } from "./RemoteHardwareConfig";
import type { SerialConfig } from "./SerialConfig";
import type { StoreForwardConfig } from "./StoreForwardConfig";
import type { TelemetryConfig } from "./TelemetryConfig";

export interface LocalModuleConfig { mqtt: MqttConfig | null, serial: SerialConfig | null, externalNotification: ExternalNotificationConfig | null, storeForward: StoreForwardConfig | null, rangeTest: RangeTestConfig | null, telemetry: TelemetryConfig | null, cannedMessage: CannedMessageConfig | null, audio: AudioConfig | null, remoteHardware: RemoteHardwareConfig | null, version: number, }