// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BluetoothConfig } from "./BluetoothConfig";
import type { DeviceConfig } from "./DeviceConfig";
import type { DisplayConfig } from "./DisplayConfig";
import type { LoRaConfig } from "./LoRaConfig";
import type { NetworkConfig } from "./NetworkConfig";
import type { PositionConfig } from "./PositionConfig";
import type { PowerConfig } from "./PowerConfig";

export interface LocalConfig { device: DeviceConfig | null, position: PositionConfig | null, power: PowerConfig | null, network: NetworkConfig | null, display: DisplayConfig | null, lora: LoRaConfig | null, bluetooth: BluetoothConfig | null, version: number, }