// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LoRaConfig { usePreset: boolean, modemPreset: number, bandwidth: number, spreadFactor: number, codingRate: number, frequencyOffset: number, region: number, hopLimit: number, txEnabled: boolean, txPower: number, channelNum: number, ignoreIncoming: Array<number>, }