// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MqttConfig { enabled: boolean, address: string, username: string, password: string, encryptionEnabled: boolean, jsonEnabled: boolean, }