// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpV4Config } from "./IpV4Config";

export interface NetworkConfig { wifiEnabled: boolean, wifiSsid: string, wifiPsk: string, ntpServer: string, ethEnabled: boolean, ethMode: number, ipv4Config: IpV4Config | null, }