// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceMetrics } from "./DeviceMetrics";
import type { Position } from "./Position";
import type { User } from "./User";

export interface NodeInfo { num: number, user: User | null, position: Position | null, snr: number, lastHeard: number, deviceMetrics: DeviceMetrics | null, }