// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OemStore { oemIconWidth: number, oemIconHeight: number, oemIconBits: Array<number>, oemFont: number, oemText: string, oemAesKey: Array<number>, }