// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeshPacket } from "./MeshPacket";

export type PayloadVariant = { packet: MeshPacket } | { wantConfigId: number } | { disconnect: boolean };