// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeshPacket } from "./MeshPacket";
import type { XModem } from "./XModem";

export type PayloadVariant = { packet: MeshPacket } | { wantConfigId: number } | { disconnect: boolean } | { xmodemPacket: XModem };