// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PowerConfig { isPowerSaving: boolean, onBatteryShutdownAfterSecs: number, adcMultiplierOverride: number, waitBluetoothSecs: number, meshSdsTimeoutSecs: number, sdsSecs: number, lsSecs: number, minWakeSecs: number, }