// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Variant } from "./Variant";

export interface Routing { variant: Variant | null, }