// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SerialConfig { enabled: boolean, echo: boolean, rxd: number, txd: number, baud: number, timeout: number, mode: number, }