// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeshPacket } from "./MeshPacket";

export interface ServiceEnvelope { packet: MeshPacket | null, channelId: string, gatewayId: string, }