// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Statistics { messagesTotal: number, messagesSaved: number, messagesMax: number, upTime: number, requests: number, requestsHistory: number, heartbeat: boolean, returnMax: number, returnWindow: number, }