// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Heartbeat } from "./Heartbeat";
import type { History } from "./History";
import type { Statistics } from "./Statistics";

export interface StoreAndForward { rr: number, stats: Statistics | null, history: History | null, heartbeat: Heartbeat | null, }