// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StoreForwardConfig { enabled: boolean, heartbeat: boolean, records: number, historyReturnMax: number, historyReturnWindow: number, }