// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TelemetryConfig { deviceUpdateInterval: number, environmentUpdateInterval: number, environmentMeasurementEnabled: boolean, environmentScreenEnabled: boolean, environmentDisplayFahrenheit: boolean, }