// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface User { id: string, longName: string, shortName: string, macaddr: Array<number>, hwModel: number, isLicensed: boolean, }