// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceMetrics } from "./DeviceMetrics";
import type { EnvironmentMetrics } from "./EnvironmentMetrics";

export type Variant = { deviceMetrics: DeviceMetrics } | { environmentMetrics: EnvironmentMetrics };