// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteDiscovery } from "./RouteDiscovery";

export type Variant = { routeRequest: RouteDiscovery } | { routeReply: RouteDiscovery } | { errorReason: number };