// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Waypoint { id: number, latitudeI: number, longitudeI: number, expire: number, locked: boolean, name: string, description: string, }