// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextPacket } from "./TextPacket";
import type { WaypointPacket } from "./WaypointPacket";

export type ChannelMessagePayload = ({ type: "text" } & TextPacket) | ({ type: "waypoint" } & WaypointPacket);
