// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMessagePayload } from "./ChannelMessagePayload";

export interface ChannelMessageWithAck { payload: ChannelMessagePayload, ack: boolean, }