// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./protobufs/Channel";
import type { ChannelMessageWithAck } from "./ChannelMessageWithAck";

export interface MeshChannel { config: Channel, lastInteraction: number, messages: Array<ChannelMessageWithAck>, }