// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageWithAck } from "./MessageWithAck";
import type { WaypointIDWithAck } from "./WaypointIDWithAck";

export type MessageType = { messageWithAck: MessageWithAck } | { waypointIDWithAck: WaypointIDWithAck };