// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessagePacket } from "./MessagePacket";

export interface MessageWithAck { packet: MessagePacket, ack: boolean, }