// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeshPacket } from "./protobufs/MeshPacket";

export interface MessagePacket { packet: MeshPacket, data: string, }