// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WaypointPacket } from "./WaypointPacket";

export interface WaypointIDWithAck { packet: WaypointPacket, waypointId: number, ack: boolean, }