FROM mcr.microsoft.com/devcontainers/typescript-node:1.1-22

RUN sudo apt update
RUN sudo apt install -y libwebkit2gtk-4.0-dev \
    build-essential \
    curl \
    wget \
    file \
    libssl-dev \
    libgtk-3-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev